import { mkdtemp, rm } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { afterEach, expect, it, vi } from 'vitest';
import { createRepositories } from '@dutydeck/storage';
import { CollaborationDelivery } from './collaboration-delivery.js';
const cleanups: Array<() => Promise<void>> = [];
afterEach(async () => { for (const close of cleanups.splice(0)) await close(); });
it('shares an hourly allowance across replies and reminders and rechecks pause after queueing', async () => {
  const directory = await mkdtemp(join(tmpdir(), 'collaboration-delivery-'));
  const repos = createRepositories(join(directory, 'test.db')), repository = repos.collaboration;
  cleanups.push(async () => { repos.close(); await rm(directory, { recursive: true, force: true }); });
  const scope = { appId: 'app', chatId: 'chat' };
  await repository.updateSettings(scope, { expectedRevision: 0, maxProactivePerHour: 1 }, 'owner');
  const begin = (id: string, kind: string) => repository.beginAction({ scope, id, kind, requesterId: 'owner', inputDigest: id, payload: {} });
  await begin('a', 'participation.reply'); await begin('b', 'schedule_delivery');
  await begin('command', 'command:create_mandate');
  const guard = new CollaborationDelivery(repository), send = vi.fn(async () => 'receipt');
  const outcomes = await Promise.allSettled([guard.run(scope, 'a', send), guard.run(scope, 'b', send)]);
  expect(outcomes.map(result => result.status)).toEqual(['fulfilled', 'rejected']); expect(send).toHaveBeenCalledTimes(1);
  await repository.updateSettings(scope, { expectedRevision: 1, maxProactivePerHour: 10 }, 'owner');
  let release!: () => void;
  const first = guard.run(scope, 'a', () => new Promise<void>(resolve => { release = resolve; }));
  while (!release) await new Promise(resolve => setTimeout(resolve, 1));
  const second = guard.run(scope, 'b', send);
  const rejected = expect(second).rejects.toMatchObject({ code: 'COLLABORATION_DELIVERY_SUPPRESSED' });
  await repository.updateSettings(scope, { expectedRevision: 2, notificationsPaused: true }, 'owner');
  release(); await first; await rejected; expect(send).toHaveBeenCalledTimes(1);
});
