import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Bot, Check, ExternalLink, Eye, EyeOff, FolderOpen, Plus, RefreshCw, Trash2, Wrench, X } from 'lucide-react';
import { validateHighRiskPattern } from '@dockmux/shared';
import { api, type Agent, type RiskControlMode } from '../api';
import { agentModelsQueryKey, loadAgentModels, readCachedAgentModels } from '../model-cache';
import { IconButton } from './ui';
import { ConfirmDialog } from './ConfirmDialog';
import { AgentSelect, CompactSelect } from './CompactSelect';
import { MemberNameTagInput } from './MemberNameTagInput';

export type LarkConfigModalProps = { agents: Agent[]; onClose(): void };

export function LarkConfigModal({ agents, onClose }: LarkConfigModalProps) {
  const qc = useQueryClient();
  const config = useQuery({ queryKey: ['lark-config'], queryFn: api.larkConfig });
  const capabilities = useQuery({ queryKey: ['system-capabilities'], queryFn: api.systemCapabilities });
  const [confirmation, setConfirmation] = useState<'incomplete' | 'discard' | 'delete'>();
  const [openPlatformJobId, setOpenPlatformJobId] = useState('');
  const hydratedSelection = useRef<string | null>(null);
  const enableListeningAfterNewBot = useRef(false);
  const [selectedAppId, setSelectedAppId] = useState<string | null>(null); const [step, setStep] = useState<1 | 2>(1); const [name, setName] = useState(''); const [workspace, setWorkspace] = useState(''); const [webBaseUrl, setWebBaseUrl] = useState(typeof window !== 'undefined' ? window.location.origin : ''); const [appId, setAppId] = useState(''); const [appSecret, setAppSecret] = useState(''); const [restrictUsers, setRestrictUsers] = useState(false); const [allowedUserNames, setAllowedUserNames] = useState<string[]>([]); const [allowedBotNames, setAllowedBotNames] = useState<string[]>([]); const [peerBotsAllowed, setPeerBotsAllowed] = useState(true); const [defaultAgentId, setDefaultAgentId] = useState(''); const [defaultModel, setDefaultModel] = useState(''); const [defaultReasoningEffort, setDefaultReasoningEffort] = useState(''); const [fullTrustConfirmed, setFullTrustConfirmed] = useState(false); const [preInjectPrompt, setPreInjectPrompt] = useState(''); const [groupToolsEnabled, setGroupToolsEnabled] = useState(false); const [groupToolsAllowSend, setGroupToolsAllowSend] = useState(false); const [highRiskAllowedUserNames, setHighRiskAllowedUserNames] = useState<string[]>([]); const [highRiskPattern, setHighRiskPattern] = useState(''); const [riskControlMode, setRiskControlMode] = useState<RiskControlMode>('off'); const [showSecret, setShowSecret] = useState(false); const [listening, setListening] = useState(false); const [pushIntervalMs, setPushIntervalMs] = useState(1000); const [traceLimit, setTraceLimit] = useState('50');
  const current = config.data?.bots.find(bot => bot.appId === selectedAppId);
  const highRiskPatternValidation = useMemo(() => validateHighRiskPattern(highRiskPattern), [highRiskPattern]);
  const hookStatus = useQuery({ queryKey: ['lark-hook-status', current?.appId, defaultAgentId], queryFn: () => api.larkHookStatus(current!.appId, defaultAgentId), enabled: Boolean(current && defaultAgentId && riskControlMode === 'enforced' && step === 2) });
  const agentOptions = useQuery({ queryKey: agentModelsQueryKey(defaultAgentId, defaultModel), queryFn: () => loadAgentModels(defaultAgentId, defaultModel || undefined), enabled: Boolean(defaultAgentId), initialData: () => readCachedAgentModels(defaultAgentId, defaultModel || undefined), initialDataUpdatedAt: 0, refetchOnMount: 'always', staleTime: 5 * 60_000 });
  const openPlatformJob = useQuery({
    queryKey: ['lark-open-platform-job', openPlatformJobId],
    queryFn: () => api.larkOpenPlatformSetupJob(openPlatformJobId),
    enabled: Boolean(openPlatformJobId),
    refetchInterval: query => ['preparing', 'waiting_for_scan', 'configuring'].includes(query.state.data?.status ?? '') ? 1_000 : false
  });
  const startOpenPlatformSetup = useMutation({
    mutationFn: (forceLogin: boolean) => api.startLarkOpenPlatformSetup(appId.trim(), forceLogin),
    onSuccess: job => { setOpenPlatformJobId(job.id); qc.setQueryData(['lark-open-platform-job', job.id], job); }
  });
  const enforcedHookReady = Boolean(hookStatus.data?.supported && hookStatus.data.installed && hookStatus.data.writable);
  const legacyHighRiskNeedsMigration = Boolean(riskControlMode !== 'off' && current?.highRiskAllowedEmails.length && !highRiskAllowedUserNames.length);
  useEffect(() => {
    if (!agentOptions.data || agentOptions.isFetching || !defaultReasoningEffort) return;
    if (!agentOptions.data.reasoningEfforts.some(option => option.id === defaultReasoningEffort)) setDefaultReasoningEffort('');
  }, [agentOptions.data, agentOptions.isFetching, defaultReasoningEffort]);
  useEffect(() => {
    if (!config.data || selectedAppId !== null) return;
    const firstBot = config.data.bots[0];
    setSelectedAppId(firstBot?.appId ?? '');
    setStep(firstBot && !firstBot.setupComplete ? 2 : 1);
  }, [config.data, selectedAppId]);
  useEffect(() => {
    if (!config.data || selectedAppId === null) return;
    if (hydratedSelection.current === selectedAppId) return;
    hydratedSelection.current = selectedAppId;
    const bot = config.data.bots.find(item => item.appId === selectedAppId);
    setName(bot?.name ?? ''); setWorkspace(bot?.workspace ?? ''); setWebBaseUrl(bot?.webBaseUrl ?? (typeof window !== 'undefined' ? window.location.origin : '')); setAppId(bot?.appId ?? ''); setAppSecret(''); setOpenPlatformJobId(''); setRestrictUsers(Boolean(bot?.allowedUsers.length || bot?.allowedEmails.length)); setAllowedUserNames((bot?.allowedUsers ?? []).map(user => user.name)); setAllowedBotNames((bot?.allowedBots ?? []).map(b => b.name)); setPeerBotsAllowed(bot?.peerBotsAllowed !== false);
    setDefaultAgentId(agents.some(agent => agent.id === bot?.defaultAgentId) ? bot?.defaultAgentId ?? '' : agents[0]?.id ?? '');
    setDefaultModel(bot?.defaultModel ?? ''); setDefaultReasoningEffort(bot?.defaultReasoningEffort ?? ''); setFullTrustConfirmed(bot?.fullTrustConfirmed ?? false); setListening(enableListeningAfterNewBot.current ? true : bot?.listening ?? true); enableListeningAfterNewBot.current = false; setPushIntervalMs(bot?.pushIntervalMs ?? 1000); setTraceLimit((bot?.traceLimit ?? 10).toString());
    setPreInjectPrompt(bot?.preInjectPrompt ?? ''); setGroupToolsEnabled(bot?.groupToolsEnabled ?? false); setGroupToolsAllowSend(bot?.groupToolsAllowSend ?? false); setHighRiskAllowedUserNames((bot?.highRiskAllowedUsers ?? []).map(user => user.name)); setHighRiskPattern(bot?.highRiskPattern ?? ''); setRiskControlMode(bot?.riskControlMode ?? 'off');
  }, [config.data, agents, selectedAppId]);
  const inspect = useMutation({ mutationFn: () => api.inspectLarkBot({ appId: appId.trim(), appSecret: appSecret.trim() }), onSuccess: result => setName(result.appName) });
  const save = useMutation({
    mutationFn: () => step === 1
      ? api.saveLarkConfig({ stage: 'lark', ...(current ? { originalAppId: current.appId } : {}), appId: appId.trim(), ...(appSecret.trim() ? { appSecret: appSecret.trim() } : {}), workspace: workspace.trim(), webBaseUrl: webBaseUrl.trim(), allowedUserNames: restrictUsers ? allowedUserNames : [], allowedEmails: [], allowedBotNames, peerBotsAllowed, pushIntervalMs, traceLimit: Number(traceLimit) })
      : api.saveLarkConfig({ stage: 'agent', originalAppId: current!.appId, defaultAgentId, defaultModel, defaultReasoningEffort, fullTrustConfirmed, preInjectPrompt, listening, groupToolsEnabled, groupToolsAllowSend, highRiskAllowedUserNames, highRiskAllowedEmails: [], highRiskPattern, riskControlMode }),
    onSuccess: data => { if (step === 1 && !current) enableListeningAfterNewBot.current = true; qc.setQueryData(['lark-config'], data); const savedId = appId.trim(); setSelectedAppId(savedId); setAppSecret(''); void qc.invalidateQueries({ queryKey: ['lark-hook-status', savedId] }); if (step === 1) setStep(2); else onClose(); }
  });
  const installHook = useMutation({
    mutationFn: async () => {
      const saved = await api.saveLarkConfig({ stage: 'agent', originalAppId: current!.appId, defaultAgentId, defaultModel, defaultReasoningEffort, fullTrustConfirmed, preInjectPrompt, listening, groupToolsEnabled, groupToolsAllowSend, highRiskAllowedUserNames, highRiskAllowedEmails: [], highRiskPattern, riskControlMode: 'guidance' });
      qc.setQueryData(['lark-config'], saved);
      return api.installLarkHook(current!.appId, highRiskPattern);
    },
    onSuccess: result => { qc.setQueryData(['lark-hook-status', current!.appId, defaultAgentId], result); setRiskControlMode('enforced'); void qc.invalidateQueries({ queryKey: ['lark-config'] }); }
  });
  const remove = useMutation({ mutationFn: () => api.deleteLarkConfig(current!.appId), onSuccess: data => { qc.setQueryData(['lark-config'], data); const firstBot = data.bots[0]; setSelectedAppId(firstBot?.appId ?? ''); setStep(firstBot && !firstBot.setupComplete ? 2 : 1); setConfirmation(undefined); } });
  const pickWorkspace = useMutation({ mutationFn: api.selectDirectory, onSuccess: result => setWorkspace(result.path) });
  const agentCapabilitiesPending = step === 2 && Boolean(defaultAgentId) && !agentOptions.data && (agentOptions.isLoading || agentOptions.isFetching);
  const agentCapabilitiesReady = step !== 2 || Boolean(agentOptions.data);
  const canSave = step === 1
    ? Boolean(appId.trim() && (current || appSecret.trim()) && (!restrictUsers || allowedUserNames.length) && Number.isInteger(pushIntervalMs) && pushIntervalMs >= 500 && pushIntervalMs <= 20000)
    : Boolean(current && defaultAgentId && fullTrustConfirmed && agentCapabilitiesReady && (riskControlMode === 'off' || highRiskPatternValidation.valid) && !legacyHighRiskNeedsMigration && (riskControlMode !== 'enforced' || enforcedHookReady));
  const formError = save.error ?? remove.error ?? pickWorkspace.error ?? inspect.error ?? startOpenPlatformSetup.error ?? openPlatformJob.error ?? installHook.error ?? (agentOptions.data ? undefined : agentOptions.error) ?? hookStatus.error ?? config.error;
  const permissionSettingsUrl = /^cli_[\w-]+$/.test(appId.trim()) ? `https://open.larkoffice.com/app/${encodeURIComponent(appId.trim())}/auth` : undefined;
  const permissionRelatedError = Boolean(formError && /权限|permission|通讯录|邮箱|open[_ ]?id|资源点|visible range/i.test(formError.message));
  const requestClose = () => {
    const incompleteDraft = Boolean(current && !current.setupComplete);
    const unsavedNewBot = !current && selectedAppId === '' && Boolean(appId.trim() || appSecret.trim() || workspace.trim());
    if (incompleteDraft || unsavedNewBot) { setConfirmation(incompleteDraft ? 'incomplete' : 'discard'); return; }
    onClose();
  };
  const inputClass = 'mt-1.5 h-9 w-full rounded-md border border-zinc-300 px-2.5 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200';
  return <><div className="ui-overlay fixed inset-0 z-30 grid place-items-center bg-zinc-950/25 p-4 backdrop-blur-[2px]" onMouseDown={event => { if (event.currentTarget === event.target) requestClose(); }}>
    <form onSubmit={event => { event.preventDefault(); if (canSave) save.mutate(); }} className="ui-dialog flex max-h-[calc(100dvh-2rem)] w-full max-w-[640px] flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-[0_20px_64px_rgba(24,24,27,.18)]">
      <div className="flex items-center border-b border-zinc-100 px-4 py-3"><div className="min-w-0"><h2 className="text-[14px] font-semibold text-zinc-900">飞书机器人</h2><p className="mt-0.5 truncate text-[11px] text-zinc-500">每个机器人拥有独立工作区和会话</p></div><div className="ml-auto flex shrink-0 items-center gap-0.5"><a href="https://open.larkoffice.com/app" target="_blank" rel="noreferrer" className="flex h-8 items-center gap-1.5 whitespace-nowrap rounded-lg px-2.5 text-[11px] font-medium text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400/50">飞书开发者后台<ExternalLink size={12}/></a><a href="https://open.larkoffice.com/page/launcher?from=backend_oneclick" target="_blank" rel="noreferrer" className="flex h-8 items-center gap-1.5 whitespace-nowrap rounded-lg px-2.5 text-[11px] font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400/50">快速创建机器人<ExternalLink size={12}/></a></div><span className="ml-1"><IconButton label="关闭" onClick={requestClose}><X size={15}/></IconButton></span></div>
      <div className="flex shrink-0 gap-1 overflow-x-auto border-b border-zinc-100 bg-zinc-50/70 px-3 py-2">
        {config.data?.bots.map(bot => <button key={bot.appId} type="button" onClick={() => { setSelectedAppId(bot.appId); setStep(bot.setupComplete ? 1 : 2); }} className={`flex h-8 max-w-[250px] shrink-0 items-center gap-1.5 rounded-lg px-2.5 text-[11px] font-medium transition-colors ${selectedAppId === bot.appId ? 'bg-white text-zinc-900 shadow-sm ring-1 ring-zinc-200' : 'text-zinc-500 hover:bg-white/70 hover:text-zinc-800'}`}><Bot size={13} className="shrink-0"/><span title={bot.name} className="min-w-0 max-w-32 truncate">{bot.tabLabel}</span>{bot.setupComplete ? <span title="配置完成" className="flex shrink-0 items-center gap-0.5 rounded bg-emerald-50 px-1 py-0.5 text-[9px] font-medium text-emerald-700"><Check size={9}/>已配置</span> : <span className="shrink-0 rounded bg-amber-100 px-1 py-0.5 text-[9px] text-amber-700">待配置</span>}{bot.activeListening && <span title="长连接已连接" className="h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500"/>}</button>)}
        <button type="button" onClick={() => { setSelectedAppId(''); setStep(1); }} className={`flex h-8 shrink-0 items-center gap-1 rounded-lg px-2.5 text-[11px] font-medium ${selectedAppId === '' ? 'bg-white text-zinc-900 shadow-sm ring-1 ring-zinc-200' : 'text-zinc-500 hover:bg-white/70 hover:text-zinc-800'}`}><Plus size={13}/>新增机器人</button>
      </div>
      <div className="space-y-3.5 overflow-y-auto px-4 py-4">
        {config.isLoading ? <div className="space-y-2.5"><div className="h-9 animate-pulse rounded-md bg-zinc-100"/><div className="h-9 animate-pulse rounded-md bg-zinc-100"/><div className="h-9 animate-pulse rounded-md bg-zinc-100"/></div> : <>
          <div className="mb-1 grid grid-cols-2 rounded-lg bg-zinc-100 p-1"><button type="button" onClick={() => setStep(1)} className={`rounded-md px-3 py-2 text-[11px] font-medium transition-colors ${step === 1 ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}><span className="mr-1.5 inline-grid h-4 w-4 place-items-center rounded-full bg-zinc-900 text-[9px] text-white">1</span>飞书与白名单</button><button type="button" disabled={!current} onClick={() => setStep(2)} className={`rounded-md px-3 py-2 text-[11px] font-medium transition-colors disabled:opacity-40 ${step === 2 ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}><span className="mr-1.5 inline-grid h-4 w-4 place-items-center rounded-full bg-zinc-900 text-[9px] text-white">2</span>Agent 与风险控制</button></div>
          <p className="-mt-1 text-[10px] leading-4 text-zinc-400">{step === 1 ? '直接填写真实姓名；点击“下一步”时会在机器人所在群中精确解析为 open_id 并统一保存。' : '选择 Agent、确认运行权限并启用监听，完成后机器人即可接收任务。'}</p>
          {step === 1 ? <>
          <div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="text-[11px] font-medium text-zinc-700">机器人名称</span><input value={name} readOnly placeholder="校验凭证后自动识别" className={`${inputClass} bg-zinc-50 text-zinc-500`}/></label><label className="block"><span className="text-[11px] font-medium text-zinc-700">App ID</span><input value={appId} onChange={event => { setAppId(event.target.value); setName(''); setOpenPlatformJobId(''); }} placeholder="cli_xxx" autoComplete="off" className={inputClass}/></label></div>
          <label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">App Secret{current && <span className="ml-2 font-normal text-zinc-400">留空不修改</span>}</span><span className="relative mt-1.5 block"><input value={appSecret} onChange={event => setAppSecret(event.target.value)} type={showSecret ? 'text' : 'password'} placeholder={current ? '已保存' : '输入 App Secret'} autoComplete="new-password" className="h-9 w-full rounded-md border border-zinc-300 px-2.5 pr-9 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200"/><button type="button" onClick={() => setShowSecret(value => !value)} aria-label={showSecret ? '隐藏 Secret' : '显示 Secret'} className="absolute right-0.5 top-0.5 grid h-8 w-8 place-items-center rounded text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700">{showSecret ? <EyeOff size={13}/> : <Eye size={13}/>}</button></span></label>
          <div className="rounded-lg border border-zinc-200 bg-zinc-50/70 p-3">
            <div className="flex items-start gap-3"><div className="min-w-0 flex-1"><div className="text-[11px] font-semibold text-zinc-800">自动配置飞书能力</div><p className="mt-0.5 text-[10px] leading-4 text-zinc-500">一次配置消息、群聊、附件、联系人、长连接事件与卡片回调，共 16 项必要权限，并保留当前应用可见范围后发布。</p></div><div className="flex shrink-0 items-center gap-1"><button type="button" disabled={!appId.trim() || startOpenPlatformSetup.isPending || ['preparing', 'waiting_for_scan', 'configuring'].includes(openPlatformJob.data?.status ?? '')} onClick={() => startOpenPlatformSetup.mutate(false)} className="flex h-8 items-center gap-1.5 rounded-md border border-zinc-300 bg-white px-2.5 text-[10px] font-medium text-zinc-700 hover:bg-zinc-100 disabled:cursor-not-allowed disabled:opacity-40">{startOpenPlatformSetup.isPending || ['preparing', 'configuring'].includes(openPlatformJob.data?.status ?? '') ? <RefreshCw size={11} className="animate-spin"/> : <Wrench size={11}/>} {openPlatformJob.data?.status === 'failed' ? '重试' : openPlatformJob.data?.status === 'completed' ? '重新配置' : '自动配置'}</button>{openPlatformJob.data?.status === 'failed' && <button type="button" disabled={startOpenPlatformSetup.isPending} onClick={() => startOpenPlatformSetup.mutate(true)} className="h-8 rounded-md px-2 text-[10px] font-medium text-zinc-500 hover:bg-zinc-100 hover:text-zinc-800 disabled:opacity-40">更换账号</button>}</div></div>
            {openPlatformJob.data?.status === 'waiting_for_scan' && openPlatformJob.data.qrDataUrl && <div className="mt-3 flex items-center gap-3 rounded-md border border-zinc-200 bg-white p-2.5"><img src={openPlatformJob.data.qrDataUrl} alt="飞书开放平台登录二维码" className="h-28 w-28 rounded bg-white"/><div className="text-[10px] leading-4 text-zinc-500"><div className="font-medium text-zinc-800">{openPlatformJob.data.scanConfirmed ? '已扫码，等待飞书确认' : '请用飞书扫码'}</div><div className="mt-1">仅用于登录开发者后台并配置当前 App ID；Cookie 私密保存在本机，不会读取或展示 App Secret。</div></div></div>}
            {openPlatformJob.data?.status === 'configuring' && <div className="mt-2 text-[10px] text-zinc-500">正在为 {openPlatformJob.data.accountName ?? '当前账号'} · {openPlatformJob.data.tenantName ?? '当前企业'} 配置并回读验证…</div>}
            {openPlatformJob.data?.status === 'completed' && <div className="mt-2 rounded-md border border-emerald-200 bg-emerald-50/70 px-2.5 py-2 text-[10px] text-emerald-800"><div className="flex items-center gap-1.5 font-medium"><Check size={11}/>已为 {openPlatformJob.data.accountName ?? '当前账号'} · {openPlatformJob.data.tenantName ?? '当前企业'} 完成配置并发布</div><div className="mt-1 flex flex-wrap gap-x-3 gap-y-0.5 text-emerald-700"><span>{openPlatformJob.data.result?.scopeCount ?? 16} 项权限</span><span>{openPlatformJob.data.result?.eventCount ?? 1} 个事件</span><span>{openPlatformJob.data.result?.callbackCount ?? 1} 个回调</span>{openPlatformJob.data.result?.versionId && <span className="font-mono">版本 {openPlatformJob.data.result.versionId}</span>}</div></div>}
            {openPlatformJob.data?.status === 'failed' && <div className="mt-2 text-[10px] leading-4 text-red-700">{openPlatformJob.data.error ?? '自动配置失败，请重试'}</div>}
          </div>
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">工作区</span><span className="mt-1.5 flex gap-2"><input value={workspace} onChange={event => setWorkspace(event.target.value)} placeholder="选择或输入绝对路径" className="h-9 min-w-0 flex-1 rounded-md border border-zinc-300 px-2.5 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200"/><button type="button" disabled={!capabilities.data?.directoryPicker || pickWorkspace.isPending} onClick={() => pickWorkspace.mutate()} className="flex h-9 shrink-0 items-center gap-1.5 rounded-md border border-zinc-300 bg-white px-3 text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-40"><FolderOpen size={13}/>{capabilities.data?.directoryPicker ? '选择' : '仅支持 Mac'}</button></span></label>
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">Web 访问地址 <span className="font-normal text-zinc-400">可选</span></span><input value={webBaseUrl} onChange={event => setWebBaseUrl(event.target.value)} placeholder="https://dockmux.example.com" className={inputClass}/><p className="mt-1 text-[10px] leading-4 text-zinc-400">配置后，飞书卡片底部会显示“查看详情”链接，指向该域名下的会话 Trace 页面。</p></label>
          {!current && <button type="button" disabled={!appId.trim() || !appSecret.trim() || inspect.isPending} onClick={() => inspect.mutate()} className="flex h-9 w-full items-center justify-center gap-2 rounded-md border border-zinc-300 bg-white text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-40">{inspect.isPending ? <RefreshCw size={12} className="animate-spin"/> : <Bot size={12}/>}校验凭证并识别机器人名称</button>}
          <div className="border-t border-zinc-100 pt-3.5">
            <div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-medium text-zinc-700">可使用机器人的成员</div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入飞书真实姓名；保存时解析为稳定的 open_id，不读取邮箱。</p></div><div className="flex shrink-0 rounded-md bg-zinc-100 p-0.5"><button type="button" onClick={() => setRestrictUsers(false)} className={`h-7 rounded px-2 text-[10px] font-medium ${!restrictUsers ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}>所有人</button><button type="button" onClick={() => setRestrictUsers(true)} className={`h-7 rounded px-2 text-[10px] font-medium ${restrictUsers ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}>指定成员</button></div></div>
            {restrictUsers && <div className="mt-3 space-y-2.5">
              {Boolean(current?.allowedEmails.length && !current.allowedUsers.length) && <div className="border-l-2 border-amber-400 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">检测到旧邮箱白名单。请重新填写真实姓名；保存后将迁移为 open_id 白名单并停止查询通讯录。</div>}
              <div><div className="text-[10px] font-medium text-zinc-500">成员真实姓名</div><MemberNameTagInput value={allowedUserNames} onChange={setAllowedUserNames} placeholder="输入姓名后按 Enter"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">支持 Enter、逗号或粘贴多行生成标签。保存时精确匹配；找不到或不同用户同名时不会保存。</p></div>
            </div>}
          </div>
          <div className="border-t border-zinc-100 pt-3.5">
            <div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-medium text-zinc-700">可调用机器人的其他机器人</div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入机器人名称；保存时在群成员中解析为 open_id。已配置的群协作 peer 机器人默认放行，无需填写。</p></div></div>
            <div className="mt-3 space-y-2.5">
              <div><div className="text-[10px] font-medium text-zinc-500">机器人名称</div><MemberNameTagInput value={allowedBotNames} onChange={setAllowedBotNames} placeholder="输入机器人名称后按 Enter"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">留空则仅允许 peer 机器人（如下方开关开启）。</p></div>
              <div className="flex items-center rounded-lg border border-zinc-200 bg-white px-3 py-2"><div className="min-w-0"><div className="text-[11px] font-medium text-zinc-800">群协作 peer 机器人默认放行</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">开启后，已配置的群协作 peer 机器人无需加入上方名单即可调用；关闭后仅上方名单内的机器人可调用。</div></div><button type="button" role="switch" aria-checked={peerBotsAllowed} onClick={() => setPeerBotsAllowed(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${peerBotsAllowed ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${peerBotsAllowed ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">飞书推送间隔<span className="ml-2 font-normal text-zinc-400">500-20000 ms</span></span><input type="number" min={500} max={20000} step={100} value={pushIntervalMs} onChange={event => setPushIntervalMs(Number(event.target.value))} className={inputClass}/></label><label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">Trace 阶段上限<span className="ml-2 font-normal text-zinc-400">默认 50</span></span><input type="number" min={1} max={200} step={1} value={traceLimit} onChange={event => setTraceLimit(event.target.value)} className={inputClass}/><p className="mt-1 text-[10px] leading-4 text-zinc-400">心跳渲染时最多保留最近 N 个执行阶段；超过飞书 24KB / 180 组件限制时仍会自动裁剪较早记录。</p></label></div>
          </> : <>
          <div><span className="flex items-center text-[11px] font-medium text-zinc-700">默认 Agent</span><AgentSelect agents={agents} value={defaultAgentId} onChange={value => { setDefaultAgentId(value); setDefaultModel(''); setDefaultReasoningEffort(''); }}/></div>
          <label className="flex items-start gap-2.5 rounded-lg border border-amber-200 bg-amber-50 px-3 py-2.5"><input type="checkbox" checked={fullTrustConfirmed} onChange={event => setFullTrustConfirmed(event.target.checked)} className="mt-0.5 h-4 w-4 rounded border-amber-400"/><span><span className="block text-[11px] font-semibold text-amber-900">确认飞书任务以 full-trust 运行</span><span className="mt-0.5 block text-[10px] leading-4 text-amber-800">无人值守 Agent 可执行本机命令和修改文件；取消确认后不能完成配置或启用监听。</span></span></label>
          <div className={`flex items-center rounded-lg border border-zinc-200 bg-white px-3 py-2.5 ${config.data?.listeningDisabled ? 'opacity-50' : ''}`}><div className="min-w-0"><div className="text-[12px] font-medium text-zinc-800">监听飞书消息</div><div className="mt-0.5 text-[10px] text-zinc-400">{config.data?.listeningDisabled ? '本次启动已通过 --no-lark-listen 禁用，保存值不受影响' : current?.activeListening ? '长连接已连接' : listening ? '完成配置后立即接收机器人消息' : '保持关闭，仅保存机器人配置'}</div></div><button type="button" role="switch" aria-label="监听飞书消息" aria-checked={listening} disabled={config.data?.listeningDisabled} onClick={() => setListening(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors disabled:cursor-not-allowed ${listening && !config.data?.listeningDisabled ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${listening ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>
          {!agentOptions.data && (agentOptions.isLoading || agentOptions.isFetching) ? <div className="flex h-9 items-center rounded-md bg-zinc-50 px-2.5 text-[11px] text-zinc-400"><RefreshCw size={12} className="mr-2 animate-spin"/>正在读取 Agent 配置</div> : <>
            {agentOptions.data?.source === 'acp' && agentOptions.data.models.length > 0 && <div><span className="text-[11px] font-medium text-zinc-700">默认模型</span><CompactSelect options={[{ value: '', label: agentOptions.data.defaultModel ? `Agent 默认 (${agentOptions.data.defaultModel})` : '使用 Agent 默认模型' }, ...agentOptions.data.models.map(item => ({ value: item.id, label: item.name, meta: item.name === item.id ? undefined : item.id }))]} value={defaultModel} placeholder="选择默认模型" disabledText="" onChange={value => { setDefaultModel(value); setDefaultReasoningEffort(''); }}/></div>}
            {agentOptions.data?.source === 'acp' && agentOptions.data.reasoningEfforts.length > 0 && <div><span className="text-[11px] font-medium text-zinc-700">推理强度</span><CompactSelect options={[{ value: '', label: agentOptions.data.defaultReasoningEffort ? `Agent 默认 (${agentOptions.data.defaultReasoningEffort})` : '使用 Agent 默认强度' }, ...agentOptions.data.reasoningEfforts.map(item => ({ value: item.id, label: item.name }))]} value={defaultReasoningEffort} placeholder="选择推理强度" disabledText="" onChange={setDefaultReasoningEffort}/></div>}
          </>}
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">预注入 Prompt <span className="font-normal text-zinc-400">可选，默认空</span></span><textarea value={preInjectPrompt} onChange={event => setPreInjectPrompt(event.target.value)} rows={3} placeholder="例如：请始终使用中文回答，并优先给出结论。" className="mt-1.5 w-full resize-y rounded-md border border-zinc-300 bg-white px-2.5 py-2 text-[12px] leading-5 outline-none placeholder:text-zinc-400 focus:border-zinc-500"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">每轮飞书对话都会在用户请求前隐式注入，不会在 Agent 聊天记录中重复显示为用户消息。</p></label>
          <div className="rounded-lg border border-zinc-200 bg-white px-3 py-2.5"><div className="flex items-center"><div className="min-w-0"><div className="text-[12px] font-medium text-zinc-800">启用 Agent 群协作工具</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">允许 Agent 在当前飞书群发现其他已配置 Agent，并读取增量消息</div></div><button type="button" role="switch" aria-checked={groupToolsEnabled} onClick={() => setGroupToolsEnabled(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${groupToolsEnabled ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${groupToolsEnabled ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>{groupToolsEnabled && <div className="mt-3 flex items-center border-t border-zinc-100 pt-3"><div className="min-w-0"><div className="text-[11px] font-medium text-zinc-800">允许 Agent 发消息与 @交接</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">关闭后仅保留 self、peers、messages 和 wait 只读能力</div></div><button type="button" role="switch" aria-checked={groupToolsAllowSend} onClick={() => setGroupToolsAllowSend(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${groupToolsAllowSend ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${groupToolsAllowSend ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>}<p className="mt-2 text-[10px] leading-4 text-zinc-400">缺少群成员、消息或发消息权限时，Agent 会停止对应操作并给出管理员授权链接；不会索要 App Secret。</p></div>
          <label className="block rounded-lg border border-zinc-200 bg-white px-3 py-2.5"><span className="text-[12px] font-medium text-zinc-800">风险控制</span><span className="mt-0.5 block text-[10px] leading-4 text-zinc-400">关闭：不附加限制；约束提示：向 Agent 注入高危操作约束；强制拦截：同时由 Agent Hook 拦截高危工具调用。</span><select aria-label="风险控制" value={riskControlMode} onChange={event => setRiskControlMode(event.target.value as RiskControlMode)} className="mt-2 h-9 w-full rounded-md border border-zinc-300 bg-white px-2.5 text-[12px] text-zinc-800 outline-none focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200"><option value="off">关闭</option><option value="guidance">约束提示</option><option value="enforced">强制拦截</option></select></label>
          {riskControlMode !== 'off' && <div className="rounded-lg border border-zinc-200 bg-zinc-50/70 p-3"><div className="text-[12px] font-semibold text-zinc-800">高危操作规则</div><p className="mt-1 text-[10px] leading-4 text-zinc-500">{riskControlMode === 'enforced' ? '未在允许名单内的发送人会收到约束提示，并由当前 Agent 的 Hook 强制拦截匹配操作。' : '未在允许名单内的发送人会收到隐式约束提示；此模式不安装或启用工具调用拦截。'}</p>
            <div className="mt-3"><div className="text-[11px] font-medium text-zinc-700">允许执行高危操作的成员 <span className="font-normal text-zinc-400">留空则继承普通成员名单</span></div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入真实姓名，保存时解析为 open_id。</p>
              {legacyHighRiskNeedsMigration && <div className="mt-2 border-l-2 border-amber-400 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">检测到旧高危邮箱名单。请重新选择成员后再保存，避免意外扩大高危权限。</div>}
              <MemberNameTagInput value={highRiskAllowedUserNames} onChange={setHighRiskAllowedUserNames} placeholder="输入姓名后按 Enter"/>
            </div>
            <label className="mt-3 block"><span className="text-[11px] font-medium text-zinc-700">高危操作正则表达式</span><textarea value={highRiskPattern} onChange={event => setHighRiskPattern(event.target.value)} rows={4} aria-invalid={!highRiskPatternValidation.valid} className={`mt-1.5 w-full resize-y rounded-md border bg-white px-2.5 py-2 font-mono text-[11px] leading-5 outline-none ${highRiskPatternValidation.valid ? 'border-zinc-300 focus:border-zinc-500' : 'border-red-300 focus:border-red-500 focus:ring-1 focus:ring-red-100'}`}/>{!highRiskPatternValidation.valid && <p className="mt-1.5 flex items-start gap-1 text-[10px] leading-4 text-red-600"><AlertTriangle size={11} className="mt-0.5 shrink-0"/>{highRiskPatternValidation.error}</p>}</label>
            {riskControlMode === 'enforced' && <div className="mt-3 border-t border-zinc-200 pt-3"><div className="text-[11px] font-medium text-zinc-800">拦截 Hook</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">{hookStatus.isLoading || hookStatus.isFetching ? '正在检查当前 Agent…' : enforcedHookReady ? `已为 ${defaultAgentId} 配置，可启用强制拦截` : hookStatus.data?.reason ?? `当前 Agent ${defaultAgentId} 尚未配置可写 Hook`}</div>{hookStatus.isSuccess && !enforcedHookReady && <button type="button" disabled={!current || installHook.isPending || legacyHighRiskNeedsMigration || !workspace.trim() || !highRiskPatternValidation.valid || hookStatus.data?.supported === false} onClick={() => installHook.mutate()} className="mt-3 flex h-9 w-full items-center justify-center gap-2 rounded-md border border-zinc-300 bg-white text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-40"><Wrench size={12}/>{installHook.isPending ? '正在配置拦截 Hook' : '配置拦截 Hook'}</button>}{hookStatus.data?.supported === false && <div className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">{hookStatus.data.reason}</div>}{hookStatus.data?.trustInstructions && <div className="mt-2 rounded-md border border-zinc-200 bg-white px-2.5 py-2 text-[10px] leading-4 text-zinc-500">{hookStatus.data.trustInstructions}</div>}</div>}
          </div>}
          </>}
        </>}
        {formError && <div className="rounded-md border border-red-100 bg-red-50 px-2.5 py-2 text-[11px] leading-4 text-red-700"><div>{formError.message}</div>{permissionRelatedError && permissionSettingsUrl && <a href={permissionSettingsUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 font-medium text-red-800 underline decoration-red-300 underline-offset-2 hover:text-red-950">打开当前机器人的权限配置<ExternalLink size={11}/></a>}</div>}
      </div>
      <div className="flex items-center border-t border-zinc-100 px-4 py-3">{current ? <button type="button" onClick={() => { remove.reset(); setConfirmation('delete'); }} className="flex items-center gap-1.5 rounded-md px-2 py-1.5 text-[11px] font-medium text-red-600 hover:bg-red-50"><Trash2 size={13}/>删除配置</button> : <span className="text-[10px] text-zinc-400">App ID 将作为唯一主键，不能重复配置</span>}{step === 2 && <button type="button" onClick={() => setStep(1)} className="ml-auto rounded-md px-3 py-1.5 text-xs font-medium text-zinc-600 hover:bg-zinc-100">上一步</button>}<button type="button" onClick={requestClose} className={`${step === 2 ? '' : 'ml-auto'} rounded-md px-3 py-1.5 text-xs font-medium text-zinc-600 hover:bg-zinc-100`}>{step === 2 && current && !current.setupComplete ? '稍后完成' : '取消'}</button><button type="submit" disabled={!canSave || save.isPending} className="ml-1 min-w-20 rounded-md bg-zinc-900 px-3 py-1.5 text-xs font-medium text-white hover:bg-zinc-700 active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-35">{save.isPending ? (step === 1 ? '验证中' : '保存中') : agentCapabilitiesPending ? '读取模型中' : step === 1 ? '下一步' : '完成配置'}</button></div>
    </form>
  </div><ConfirmDialog
    open={Boolean(confirmation)}
    tone={confirmation === 'delete' ? 'danger' : 'warning'}
    title={confirmation === 'delete' ? '删除机器人配置？' : confirmation === 'incomplete' ? '稍后再完成配置？' : '放弃未保存的配置？'}
    description={confirmation === 'delete' ? `将删除“${current?.name ?? '当前机器人'}”的凭证、监听和风险控制配置。已有会话记录不会删除。` : confirmation === 'incomplete' ? 'Agent 配置尚未完成。若已开启监听，机器人仍会接收消息，并提示发送人补充运行配置。' : '当前填写的机器人信息尚未保存，关闭后需要重新填写。'}
    confirmLabel={confirmation === 'delete' ? '确认删除' : confirmation === 'incomplete' ? '稍后完成' : '放弃修改'}
    busy={confirmation === 'delete' && remove.isPending}
    error={confirmation === 'delete' && remove.error ? remove.error.message : undefined}
    onCancel={() => { if (!remove.isPending) setConfirmation(undefined); }}
    onConfirm={() => { if (confirmation === 'delete') remove.mutate(); else { setConfirmation(undefined); onClose(); } }}
  /></>;
}
