import { useEffect, useMemo, useRef, useState } from 'react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { AlertTriangle, Bot, Check, ExternalLink, Eye, EyeOff, FolderOpen, Plus, RefreshCw, Trash2, Wrench, X } from 'lucide-react';
import { validateHighRiskPattern } from '@dockmux/shared';
import { api, type Agent } from '../api';
import { canSaveHardGate, canToggleHardGate } from '../lark-config-form';
import { agentModelsQueryKey, loadAgentModels, readCachedAgentModels } from '../model-cache';
import { IconButton } from './ui';
import { ConfirmDialog } from './ConfirmDialog';
import { AgentSelect, CompactSelect } from './CompactSelect';
import { MemberNameTagInput } from './MemberNameTagInput';

export type LarkConfigModalProps = { agents: Agent[]; onClose(): void };

export function LarkConfigModal({ agents, onClose }: LarkConfigModalProps) {
  const qc = useQueryClient();
  const config = useQuery({ queryKey: ['lark-config'], queryFn: api.larkConfig });
  const capabilities = useQuery({ queryKey: ['system-capabilities'], queryFn: api.systemCapabilities });
  const [confirmation, setConfirmation] = useState<'incomplete' | 'discard' | 'delete'>();
  const hydratedSelection = useRef<string | null>(null);
  const [selectedAppId, setSelectedAppId] = useState<string | null>(null); const [step, setStep] = useState<1 | 2>(1); const [name, setName] = useState(''); const [workspace, setWorkspace] = useState(''); const [webBaseUrl, setWebBaseUrl] = useState(typeof window !== 'undefined' ? window.location.origin : ''); const [appId, setAppId] = useState(''); const [appSecret, setAppSecret] = useState(''); const [restrictUsers, setRestrictUsers] = useState(false); const [allowedUserNames, setAllowedUserNames] = useState<string[]>([]); const [allowedBotNames, setAllowedBotNames] = useState<string[]>([]); const [peerBotsAllowed, setPeerBotsAllowed] = useState(true); const [defaultAgentId, setDefaultAgentId] = useState(''); const [defaultModel, setDefaultModel] = useState(''); const [defaultReasoningEffort, setDefaultReasoningEffort] = useState(''); const [preInjectPrompt, setPreInjectPrompt] = useState(''); const [groupToolsEnabled, setGroupToolsEnabled] = useState(false); const [groupToolsAllowSend, setGroupToolsAllowSend] = useState(false); const [highRiskAllowedUserNames, setHighRiskAllowedUserNames] = useState<string[]>([]); const [highRiskPattern, setHighRiskPattern] = useState(''); const [gateEnabled, setGateEnabled] = useState(false); const [softGateEnabled, setSoftGateEnabled] = useState(false); const [hardGateEnabled, setHardGateEnabled] = useState(false); const [hookTrustConfirmed, setHookTrustConfirmed] = useState(false); const [showSecret, setShowSecret] = useState(false); const [listening, setListening] = useState(false); const [pushIntervalMs, setPushIntervalMs] = useState(1000); const [traceLimit, setTraceLimit] = useState('50');
  const current = config.data?.bots.find(bot => bot.appId === selectedAppId);
  const agentSelectionSaved = Boolean(current?.setupComplete && current.defaultAgentId === defaultAgentId);
  const defaultAgentLocked = Boolean(hardGateEnabled || current?.hardGateEnabled);
  const highRiskPatternValidation = useMemo(() => validateHighRiskPattern(highRiskPattern), [highRiskPattern]);
  const hookStatus = useQuery({ queryKey: ['lark-hook-status', current?.appId, defaultAgentId], queryFn: () => api.larkHookStatus(current!.appId), enabled: Boolean(agentSelectionSaved && gateEnabled && step === 2) });
  const agentOptions = useQuery({ queryKey: agentModelsQueryKey(defaultAgentId, defaultModel), queryFn: () => loadAgentModels(defaultAgentId, defaultModel || undefined), enabled: Boolean(defaultAgentId), initialData: () => readCachedAgentModels(defaultAgentId, defaultModel || undefined), initialDataUpdatedAt: 0, refetchOnMount: 'always', staleTime: 5 * 60_000 });
  const hardGateFormState = { enabled: hardGateEnabled, persisted: Boolean(current?.hardGateEnabled), agentSelectionSaved, hookInstalled: Boolean(hookStatus.data?.installed) };
  const hardGateReadyToSave = canSaveHardGate(hardGateFormState);
  const hardGateCanToggle = canToggleHardGate(hardGateFormState);
  const hardGateHookMissing = Boolean(hardGateEnabled && current?.hardGateEnabled && hookStatus.isSuccess && !hookStatus.data.installed);
  const legacyHighRiskNeedsMigration = Boolean(gateEnabled && current?.highRiskAllowedEmails.length && !highRiskAllowedUserNames.length);
  useEffect(() => {
    if (!agentOptions.data || agentOptions.isFetching || !defaultReasoningEffort) return;
    if (!agentOptions.data.reasoningEfforts.some(option => option.id === defaultReasoningEffort)) setDefaultReasoningEffort('');
  }, [agentOptions.data, agentOptions.isFetching, defaultReasoningEffort]);
  useEffect(() => {
    if (!config.data || selectedAppId !== null) return;
    const firstBot = config.data.bots[0];
    setSelectedAppId(firstBot?.appId ?? '');
    setStep(firstBot && !firstBot.setupComplete ? 2 : 1);
  }, [config.data, selectedAppId]);
  useEffect(() => {
    if (!config.data || selectedAppId === null) return;
    if (hydratedSelection.current === selectedAppId) return;
    hydratedSelection.current = selectedAppId;
    const bot = config.data.bots.find(item => item.appId === selectedAppId);
    setName(bot?.name ?? ''); setWorkspace(bot?.workspace ?? ''); setWebBaseUrl(bot?.webBaseUrl ?? (typeof window !== 'undefined' ? window.location.origin : '')); setAppId(bot?.appId ?? ''); setAppSecret(''); setRestrictUsers(Boolean(bot?.allowedUsers.length || bot?.allowedEmails.length)); setAllowedUserNames((bot?.allowedUsers ?? []).map(user => user.name)); setAllowedBotNames((bot?.allowedBots ?? []).map(b => b.name)); setPeerBotsAllowed(bot?.peerBotsAllowed !== false);
    setDefaultAgentId(agents.some(agent => agent.id === bot?.defaultAgentId) ? bot?.defaultAgentId ?? '' : agents[0]?.id ?? '');
    setDefaultModel(bot?.defaultModel ?? ''); setDefaultReasoningEffort(bot?.defaultReasoningEffort ?? ''); setListening(bot?.listening ?? false); setPushIntervalMs(bot?.pushIntervalMs ?? 1000); setTraceLimit((bot?.traceLimit ?? 10).toString());
    setPreInjectPrompt(bot?.preInjectPrompt ?? ''); setGroupToolsEnabled(bot?.groupToolsEnabled ?? false); setGroupToolsAllowSend(bot?.groupToolsAllowSend ?? false); setHighRiskAllowedUserNames((bot?.highRiskAllowedUsers ?? []).map(user => user.name)); setHighRiskPattern(bot?.highRiskPattern ?? ''); setGateEnabled(bot?.gateEnabled ?? false); setSoftGateEnabled(bot?.gateEnabled ?? false); setHardGateEnabled(bot?.hardGateEnabled ?? false); setHookTrustConfirmed(bot?.hookTrustConfirmed ?? false);
  }, [config.data, agents, selectedAppId]);
  const inspect = useMutation({ mutationFn: () => api.inspectLarkBot({ appId: appId.trim(), appSecret: appSecret.trim() }), onSuccess: result => setName(result.appName) });
  const save = useMutation({
    mutationFn: () => step === 1
      ? api.saveLarkConfig({ stage: 'lark', ...(current ? { originalAppId: current.appId } : {}), appId: appId.trim(), ...(appSecret.trim() ? { appSecret: appSecret.trim() } : {}), workspace: workspace.trim(), webBaseUrl: webBaseUrl.trim(), allowedUserNames: restrictUsers ? allowedUserNames : [], allowedEmails: [], allowedBotNames, peerBotsAllowed, listening, pushIntervalMs, traceLimit: Number(traceLimit) })
      : api.saveLarkConfig({ stage: 'agent', originalAppId: current!.appId, defaultAgentId, defaultModel, defaultReasoningEffort, preInjectPrompt, groupToolsEnabled, groupToolsAllowSend, highRiskAllowedUserNames, highRiskAllowedEmails: [], highRiskPattern, gateEnabled, softGateEnabled: gateEnabled, hardGateEnabled, hookTrustConfirmed }),
    onSuccess: data => { qc.setQueryData(['lark-config'], data); const savedId = appId.trim(); setSelectedAppId(savedId); setAppSecret(''); void qc.invalidateQueries({ queryKey: ['lark-hook-status', savedId] }); if (step === 1) setStep(2); else onClose(); }
  });
  const installHook = useMutation({
    mutationFn: async () => {
      const saved = await api.saveLarkConfig({ stage: 'agent', originalAppId: current!.appId, defaultAgentId, defaultModel, defaultReasoningEffort, preInjectPrompt, listening, groupToolsEnabled, groupToolsAllowSend, highRiskAllowedUserNames, highRiskAllowedEmails: [], highRiskPattern, gateEnabled: true, softGateEnabled: true, hardGateEnabled: false, hookTrustConfirmed: false });
      qc.setQueryData(['lark-config'], saved);
      return api.installLarkHook(current!.appId, highRiskPattern);
    },
    onSuccess: result => { qc.setQueryData(['lark-hook-status', current!.appId, defaultAgentId], result); setGateEnabled(true); setSoftGateEnabled(true); setHardGateEnabled(false); setHookTrustConfirmed(true); void qc.invalidateQueries({ queryKey: ['lark-config'] }); }
  });
  const remove = useMutation({ mutationFn: () => api.deleteLarkConfig(current!.appId), onSuccess: data => { qc.setQueryData(['lark-config'], data); const firstBot = data.bots[0]; setSelectedAppId(firstBot?.appId ?? ''); setStep(firstBot && !firstBot.setupComplete ? 2 : 1); setConfirmation(undefined); } });
  const pickWorkspace = useMutation({ mutationFn: api.selectDirectory, onSuccess: result => setWorkspace(result.path) });
  const agentCapabilitiesPending = step === 2 && Boolean(defaultAgentId) && !agentOptions.data && (agentOptions.isLoading || agentOptions.isFetching);
  const agentCapabilitiesReady = step !== 2 || Boolean(agentOptions.data);
  const canSave = step === 1
    ? Boolean(appId.trim() && (current || appSecret.trim()) && (!restrictUsers || allowedUserNames.length) && Number.isInteger(pushIntervalMs) && pushIntervalMs >= 500 && pushIntervalMs <= 20000)
    : Boolean(current && defaultAgentId && agentCapabilitiesReady && (!gateEnabled || highRiskPatternValidation.valid) && !legacyHighRiskNeedsMigration && hardGateReadyToSave);
  const larkCredentialsReady = Boolean(current || (appId.trim() && appSecret.trim()));
  const formError = save.error ?? remove.error ?? pickWorkspace.error ?? inspect.error ?? installHook.error ?? (agentOptions.data ? undefined : agentOptions.error) ?? config.error;
  const permissionSettingsUrl = /^cli_[\w-]+$/.test(appId.trim()) ? `https://open.larkoffice.com/app/${encodeURIComponent(appId.trim())}/auth` : undefined;
  const permissionRelatedError = Boolean(formError && /权限|permission|通讯录|邮箱|open[_ ]?id|资源点|visible range/i.test(formError.message));
  const requestClose = () => {
    const incompleteDraft = Boolean(current && !current.setupComplete);
    const unsavedNewBot = !current && selectedAppId === '' && Boolean(appId.trim() || appSecret.trim() || workspace.trim());
    if (incompleteDraft || unsavedNewBot) { setConfirmation(incompleteDraft ? 'incomplete' : 'discard'); return; }
    onClose();
  };
  const inputClass = 'mt-1.5 h-9 w-full rounded-md border border-zinc-300 px-2.5 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200';
  return <><div className="ui-overlay fixed inset-0 z-30 grid place-items-center bg-zinc-950/25 p-4 backdrop-blur-[2px]" onMouseDown={event => { if (event.currentTarget === event.target) requestClose(); }}>
    <form onSubmit={event => { event.preventDefault(); if (canSave) save.mutate(); }} className="ui-dialog flex max-h-[calc(100dvh-2rem)] w-full max-w-[640px] flex-col overflow-hidden rounded-xl border border-zinc-200 bg-white shadow-[0_20px_64px_rgba(24,24,27,.18)]">
      <div className="flex items-center border-b border-zinc-100 px-4 py-3"><div className="min-w-0"><h2 className="text-[14px] font-semibold text-zinc-900">飞书机器人</h2><p className="mt-0.5 truncate text-[11px] text-zinc-500">每个机器人拥有独立工作区和会话</p></div><div className="ml-auto flex shrink-0 items-center gap-0.5"><a href="https://open.larkoffice.com/app" target="_blank" rel="noreferrer" className="flex h-8 items-center gap-1.5 whitespace-nowrap rounded-lg px-2.5 text-[11px] font-medium text-zinc-500 transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400/50">飞书开发者后台<ExternalLink size={12}/></a><a href="https://open.larkoffice.com/page/launcher?from=backend_oneclick" target="_blank" rel="noreferrer" className="flex h-8 items-center gap-1.5 whitespace-nowrap rounded-lg px-2.5 text-[11px] font-medium text-zinc-600 transition-colors hover:bg-zinc-100 hover:text-zinc-900 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-zinc-400/50">快速创建机器人<ExternalLink size={12}/></a></div><span className="ml-1"><IconButton label="关闭" onClick={requestClose}><X size={15}/></IconButton></span></div>
      <div className="flex shrink-0 gap-1 overflow-x-auto border-b border-zinc-100 bg-zinc-50/70 px-3 py-2">
        {config.data?.bots.map(bot => <button key={bot.appId} type="button" onClick={() => { setSelectedAppId(bot.appId); setStep(bot.setupComplete ? 1 : 2); }} className={`flex h-8 max-w-[250px] shrink-0 items-center gap-1.5 rounded-lg px-2.5 text-[11px] font-medium transition-colors ${selectedAppId === bot.appId ? 'bg-white text-zinc-900 shadow-sm ring-1 ring-zinc-200' : 'text-zinc-500 hover:bg-white/70 hover:text-zinc-800'}`}><Bot size={13} className="shrink-0"/><span title={bot.name} className="min-w-0 max-w-32 truncate">{bot.tabLabel}</span>{bot.setupComplete ? <span title="配置完成" className="flex shrink-0 items-center gap-0.5 rounded bg-emerald-50 px-1 py-0.5 text-[9px] font-medium text-emerald-700"><Check size={9}/>已配置</span> : <span className="shrink-0 rounded bg-amber-100 px-1 py-0.5 text-[9px] text-amber-700">待配置</span>}{bot.activeListening && <span title="长连接已连接" className="h-1.5 w-1.5 shrink-0 rounded-full bg-emerald-500"/>}</button>)}
        <button type="button" onClick={() => { setSelectedAppId(''); setStep(1); }} className={`flex h-8 shrink-0 items-center gap-1 rounded-lg px-2.5 text-[11px] font-medium ${selectedAppId === '' ? 'bg-white text-zinc-900 shadow-sm ring-1 ring-zinc-200' : 'text-zinc-500 hover:bg-white/70 hover:text-zinc-800'}`}><Plus size={13}/>新增机器人</button>
      </div>
      <div className="space-y-3.5 overflow-y-auto px-4 py-4">
        {config.isLoading ? <div className="space-y-2.5"><div className="h-9 animate-pulse rounded-md bg-zinc-100"/><div className="h-9 animate-pulse rounded-md bg-zinc-100"/><div className="h-9 animate-pulse rounded-md bg-zinc-100"/></div> : <>
          <div className="mb-1 grid grid-cols-2 rounded-lg bg-zinc-100 p-1"><button type="button" onClick={() => setStep(1)} className={`rounded-md px-3 py-2 text-[11px] font-medium transition-colors ${step === 1 ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}><span className="mr-1.5 inline-grid h-4 w-4 place-items-center rounded-full bg-zinc-900 text-[9px] text-white">1</span>飞书与白名单</button><button type="button" disabled={!current} onClick={() => { if (step === 1 && canSave) save.mutate(); else if (step !== 2) setStep(2); }} className={`rounded-md px-3 py-2 text-[11px] font-medium transition-colors disabled:opacity-40 ${step === 2 ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}><span className="mr-1.5 inline-grid h-4 w-4 place-items-center rounded-full bg-zinc-900 text-[9px] text-white">2</span>Agent 与门禁</button></div>
          <p className="-mt-1 text-[10px] leading-4 text-zinc-400">{step === 1 ? '直接填写真实姓名；点击“下一步”时会在机器人所在群中精确解析为 open_id 并统一保存。' : 'Agent 配置不影响长连接；收到消息时才会校验运行配置。'}</p>
          {step === 1 ? <>
          <div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="text-[11px] font-medium text-zinc-700">机器人名称</span><input value={name} readOnly placeholder="校验凭证后自动识别" className={`${inputClass} bg-zinc-50 text-zinc-500`}/></label><label className="block"><span className="text-[11px] font-medium text-zinc-700">App ID</span><input value={appId} onChange={event => { setAppId(event.target.value); setName(''); }} placeholder="cli_xxx" autoComplete="off" className={inputClass}/></label></div>
          <label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">App Secret{current && <span className="ml-2 font-normal text-zinc-400">留空不修改</span>}</span><span className="relative mt-1.5 block"><input value={appSecret} onChange={event => setAppSecret(event.target.value)} type={showSecret ? 'text' : 'password'} placeholder={current ? '已保存' : '输入 App Secret'} autoComplete="new-password" className="h-9 w-full rounded-md border border-zinc-300 px-2.5 pr-9 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200"/><button type="button" onClick={() => setShowSecret(value => !value)} aria-label={showSecret ? '隐藏 Secret' : '显示 Secret'} className="absolute right-0.5 top-0.5 grid h-8 w-8 place-items-center rounded text-zinc-400 hover:bg-zinc-100 hover:text-zinc-700">{showSecret ? <EyeOff size={13}/> : <Eye size={13}/>}</button></span></label>
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">工作区</span><span className="mt-1.5 flex gap-2"><input value={workspace} onChange={event => setWorkspace(event.target.value)} placeholder="选择或输入绝对路径" className="h-9 min-w-0 flex-1 rounded-md border border-zinc-300 px-2.5 font-mono text-[12px] outline-none placeholder:text-zinc-400 focus:border-zinc-500 focus:ring-1 focus:ring-zinc-200"/><button type="button" disabled={!capabilities.data?.directoryPicker || pickWorkspace.isPending} onClick={() => pickWorkspace.mutate()} className="flex h-9 shrink-0 items-center gap-1.5 rounded-md border border-zinc-300 bg-white px-3 text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-40"><FolderOpen size={13}/>{capabilities.data?.directoryPicker ? '选择' : '仅支持 Mac'}</button></span></label>
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">Web 访问地址 <span className="font-normal text-zinc-400">可选</span></span><input value={webBaseUrl} onChange={event => setWebBaseUrl(event.target.value)} placeholder="https://dockmux.example.com" className={inputClass}/><p className="mt-1 text-[10px] leading-4 text-zinc-400">配置后，飞书卡片底部会显示“查看详情”链接，指向该域名下的会话 Trace 页面。</p></label>
          {!current && <button type="button" disabled={!appId.trim() || !appSecret.trim() || inspect.isPending} onClick={() => inspect.mutate()} className="flex h-9 w-full items-center justify-center gap-2 rounded-md border border-zinc-300 bg-white text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:opacity-40">{inspect.isPending ? <RefreshCw size={12} className="animate-spin"/> : <Bot size={12}/>}校验凭证并识别机器人名称</button>}
          <div className="border-t border-zinc-100 pt-3.5">
            <div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-medium text-zinc-700">可使用机器人的成员</div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入飞书真实姓名；保存时解析为稳定的 open_id，不读取邮箱。</p></div><div className="flex shrink-0 rounded-md bg-zinc-100 p-0.5"><button type="button" onClick={() => setRestrictUsers(false)} className={`h-7 rounded px-2 text-[10px] font-medium ${!restrictUsers ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}>所有人</button><button type="button" onClick={() => setRestrictUsers(true)} className={`h-7 rounded px-2 text-[10px] font-medium ${restrictUsers ? 'bg-white text-zinc-900 shadow-sm' : 'text-zinc-500'}`}>指定成员</button></div></div>
            {restrictUsers && <div className="mt-3 space-y-2.5">
              {Boolean(current?.allowedEmails.length && !current.allowedUsers.length) && <div className="border-l-2 border-amber-400 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">检测到旧邮箱白名单。请重新填写真实姓名；保存后将迁移为 open_id 白名单并停止查询通讯录。</div>}
              <div><div className="text-[10px] font-medium text-zinc-500">成员真实姓名</div><MemberNameTagInput value={allowedUserNames} onChange={setAllowedUserNames} placeholder="输入姓名后按 Enter"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">支持 Enter、逗号或粘贴多行生成标签。保存时精确匹配；找不到或不同用户同名时不会保存。</p></div>
            </div>}
          </div>
          <div className="border-t border-zinc-100 pt-3.5">
            <div className="flex items-start justify-between gap-3"><div><div className="text-[11px] font-medium text-zinc-700">可调用机器人的其他机器人</div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入机器人名称；保存时在群成员中解析为 open_id。已配置的群协作 peer 机器人默认放行，无需填写。</p></div></div>
            <div className="mt-3 space-y-2.5">
              <div><div className="text-[10px] font-medium text-zinc-500">机器人名称</div><MemberNameTagInput value={allowedBotNames} onChange={setAllowedBotNames} placeholder="输入机器人名称后按 Enter"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">留空则仅允许 peer 机器人（如下方开关开启）。</p></div>
              <div className="flex items-center rounded-lg border border-zinc-200 bg-white px-3 py-2"><div className="min-w-0"><div className="text-[11px] font-medium text-zinc-800">群协作 peer 机器人默认放行</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">开启后，已配置的群协作 peer 机器人无需加入上方名单即可调用；关闭后仅上方名单内的机器人可调用。</div></div><button type="button" role="switch" aria-checked={peerBotsAllowed} onClick={() => setPeerBotsAllowed(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${peerBotsAllowed ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${peerBotsAllowed ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>
            </div>
          </div>
          <div className="grid gap-3 sm:grid-cols-2"><label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">飞书推送间隔<span className="ml-2 font-normal text-zinc-400">500-20000 ms</span></span><input type="number" min={500} max={20000} step={100} value={pushIntervalMs} onChange={event => setPushIntervalMs(Number(event.target.value))} className={inputClass}/></label><label className="block"><span className="flex items-center text-[11px] font-medium text-zinc-700">Trace 阶段上限<span className="ml-2 font-normal text-zinc-400">默认 50</span></span><input type="number" min={1} max={200} step={1} value={traceLimit} onChange={event => setTraceLimit(event.target.value)} className={inputClass}/><p className="mt-1 text-[10px] leading-4 text-zinc-400">心跳渲染时最多保留最近 N 个执行阶段；超过飞书 24KB / 180 组件限制时仍会自动裁剪较早记录。</p></label></div>
          <div className="border-t border-zinc-100 pt-3.5">
            <div className={`flex items-center ${config.data?.listeningDisabled || !larkCredentialsReady ? 'opacity-50' : ''}`}><div className="min-w-0"><div className="text-[12px] font-medium text-zinc-800">监听飞书消息</div><div className="mt-0.5 text-[10px] text-zinc-400">{config.data?.listeningDisabled ? '本次启动已通过 --no-lark-listen 禁用，保存值不受影响' : !larkCredentialsReady ? '请先填写飞书凭证' : current?.activeListening ? '长连接已连接' : !current?.setupComplete ? '可先监听；收到消息时再校验 Agent 运行配置' : '使用长连接接收机器人消息'}</div></div><button type="button" role="switch" aria-checked={listening} disabled={config.data?.listeningDisabled || !larkCredentialsReady} onClick={() => setListening(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors disabled:cursor-not-allowed ${listening && !config.data?.listeningDisabled && larkCredentialsReady ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${listening ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>
          </div>
          </> : <>
          <div><span className="flex items-center text-[11px] font-medium text-zinc-700">默认 Agent{defaultAgentLocked && <span className="ml-2 font-normal text-zinc-400">硬门禁已开启，保存关闭后解锁</span>}</span><AgentSelect agents={agents} value={defaultAgentId} disabled={defaultAgentLocked} onChange={value => { setDefaultAgentId(value); setDefaultModel(''); setDefaultReasoningEffort(''); setHardGateEnabled(false); setHookTrustConfirmed(false); }}/></div>
          {!agentOptions.data && (agentOptions.isLoading || agentOptions.isFetching) ? <div className="flex h-9 items-center rounded-md bg-zinc-50 px-2.5 text-[11px] text-zinc-400"><RefreshCw size={12} className="mr-2 animate-spin"/>正在读取 Agent 配置</div> : <>
            {agentOptions.data?.source === 'acp' && agentOptions.data.models.length > 0 && <div><span className="text-[11px] font-medium text-zinc-700">默认模型</span><CompactSelect options={[{ value: '', label: agentOptions.data.defaultModel ? `Agent 默认 (${agentOptions.data.defaultModel})` : '使用 Agent 默认模型' }, ...agentOptions.data.models.map(item => ({ value: item.id, label: item.name, meta: item.name === item.id ? undefined : item.id }))]} value={defaultModel} placeholder="选择默认模型" disabledText="" onChange={value => { setDefaultModel(value); setDefaultReasoningEffort(''); }}/></div>}
            {agentOptions.data?.source === 'acp' && agentOptions.data.reasoningEfforts.length > 0 && <div><span className="text-[11px] font-medium text-zinc-700">推理强度</span><CompactSelect options={[{ value: '', label: agentOptions.data.defaultReasoningEffort ? `Agent 默认 (${agentOptions.data.defaultReasoningEffort})` : '使用 Agent 默认强度' }, ...agentOptions.data.reasoningEfforts.map(item => ({ value: item.id, label: item.name }))]} value={defaultReasoningEffort} placeholder="选择推理强度" disabledText="" onChange={setDefaultReasoningEffort}/></div>}
          </>}
          <label className="block"><span className="text-[11px] font-medium text-zinc-700">预注入 Prompt <span className="font-normal text-zinc-400">可选，默认空</span></span><textarea value={preInjectPrompt} onChange={event => setPreInjectPrompt(event.target.value)} rows={3} placeholder="例如：请始终使用中文回答，并优先给出结论。" className="mt-1.5 w-full resize-y rounded-md border border-zinc-300 bg-white px-2.5 py-2 text-[12px] leading-5 outline-none placeholder:text-zinc-400 focus:border-zinc-500"/><p className="mt-1 text-[10px] leading-4 text-zinc-400">每轮飞书对话都会在用户请求前隐式注入，不会在 Agent 聊天记录中重复显示为用户消息。</p></label>
          <div className="rounded-lg border border-zinc-200 bg-white px-3 py-2.5"><div className="flex items-center"><div className="min-w-0"><div className="text-[12px] font-medium text-zinc-800">启用 Agent 群协作工具</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">允许 Agent 在当前飞书群发现其他已配置 Agent，并读取增量消息</div></div><button type="button" role="switch" aria-checked={groupToolsEnabled} onClick={() => setGroupToolsEnabled(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${groupToolsEnabled ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${groupToolsEnabled ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>{groupToolsEnabled && <div className="mt-3 flex items-center border-t border-zinc-100 pt-3"><div className="min-w-0"><div className="text-[11px] font-medium text-zinc-800">允许 Agent 发消息与 @交接</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">关闭后仅保留 self、peers、messages 和 wait 只读能力</div></div><button type="button" role="switch" aria-checked={groupToolsAllowSend} onClick={() => setGroupToolsAllowSend(value => !value)} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${groupToolsAllowSend ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${groupToolsAllowSend ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>}<p className="mt-2 text-[10px] leading-4 text-zinc-400">缺少群成员、消息或发消息权限时，Agent 会停止对应操作并给出管理员授权链接；不会索要 App Secret。</p></div>
          <div className="flex items-center rounded-lg border border-zinc-200 bg-white px-3 py-2.5"><div className="min-w-0"><div className="text-[12px] font-medium text-zinc-800">启用高危操作门禁</div><div className="mt-0.5 text-[10px] leading-4 text-zinc-400">启用后强制开启软门禁，并可继续配置 Hook 硬门禁</div></div><button type="button" role="switch" aria-checked={gateEnabled} onClick={() => { const next = !gateEnabled; setGateEnabled(next); setSoftGateEnabled(next); if (!next) setHardGateEnabled(false); }} className={`ml-auto flex h-5 w-9 shrink-0 items-center rounded-full p-0.5 transition-colors ${gateEnabled ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${gateEnabled ? 'translate-x-4' : 'translate-x-0'}`}/></button></div>
          {gateEnabled && <div className="rounded-lg border border-zinc-200 bg-zinc-50/70 p-3"><div className="text-[12px] font-semibold text-zinc-800">高危操作门禁</div><p className="mt-1 text-[10px] leading-4 text-zinc-500">不在允许名单内的发送人会收到软门禁 Prompt；开启硬门禁后，再通过 ACP 权限层和 Agent 原生工具调用 Hook 拦截。</p>
            <div className="mt-3"><div className="text-[11px] font-medium text-zinc-700">允许执行高危操作的成员 <span className="font-normal text-zinc-400">留空则继承普通成员名单</span></div><p className="mt-0.5 text-[10px] leading-4 text-zinc-400">输入真实姓名，保存时解析为 open_id。</p>
              {legacyHighRiskNeedsMigration && <div className="mt-2 border-l-2 border-amber-400 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">检测到旧高危邮箱名单。请重新选择成员后再保存，避免意外扩大高危权限。</div>}
              <MemberNameTagInput value={highRiskAllowedUserNames} onChange={setHighRiskAllowedUserNames} placeholder="输入姓名后按 Enter"/>
            </div>
            <label className="mt-3 block"><span className="text-[11px] font-medium text-zinc-700">高危操作正则表达式</span><textarea value={highRiskPattern} onChange={event => setHighRiskPattern(event.target.value)} rows={4} aria-invalid={!highRiskPatternValidation.valid} className={`mt-1.5 w-full resize-y rounded-md border bg-white px-2.5 py-2 font-mono text-[11px] leading-5 outline-none ${highRiskPatternValidation.valid ? 'border-zinc-300 focus:border-zinc-500' : 'border-red-300 focus:border-red-500 focus:ring-1 focus:ring-red-100'}`}/>{!highRiskPatternValidation.valid && <p className="mt-1.5 flex items-start gap-1 text-[10px] leading-4 text-red-600"><AlertTriangle size={11} className="mt-0.5 shrink-0"/>{highRiskPatternValidation.error}</p>}</label>
            <div className="mt-3 flex items-center"><div><div className="text-[11px] font-medium text-zinc-800">软门禁</div><div className="text-[10px] text-zinc-400">门禁启用后固定开启，隐式注入禁止绕过的安全 Prompt</div></div><button type="button" role="switch" aria-checked disabled className="ml-auto flex h-5 w-9 cursor-not-allowed items-center rounded-full bg-zinc-900 p-0.5"><span className="h-4 w-4 translate-x-4 rounded-full bg-white shadow-sm"/></button></div>
            <div className={`mt-3 flex items-center ${!hookStatus.data?.installed && !hardGateEnabled ? 'opacity-60' : ''}`}><div><div className="text-[11px] font-medium text-zinc-800">硬门禁</div><div className="text-[10px] text-zinc-400">{hookStatus.data?.installed ? 'Hook 已配置，可以开启硬门禁' : agentSelectionSaved ? hookStatus.data?.reason ?? '请先检测并配置 Hook' : '点击下方按钮会先保存当前默认 Agent，再检测并配置 Hook'}</div></div><button type="button" role="switch" aria-checked={hardGateEnabled} disabled={!hardGateCanToggle} onClick={() => setHardGateEnabled(value => !value)} className={`ml-auto flex h-5 w-9 items-center rounded-full p-0.5 disabled:cursor-not-allowed ${hardGateEnabled ? 'bg-zinc-900' : 'bg-zinc-300'}`}><span className={`h-4 w-4 rounded-full bg-white shadow-sm transition-transform ${hardGateEnabled ? 'translate-x-4' : ''}`}/></button></div>
            {hardGateHookMissing && <div className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">已保存的硬门禁 Hook 当前未检测到。其他设置仍可保存；如需恢复硬门禁，请先关闭上方开关，再重新检测并配置 Hook。</div>}
            <button type="button" disabled={!current || hardGateEnabled || installHook.isPending || legacyHighRiskNeedsMigration || !workspace.trim() || !highRiskPatternValidation.valid || hookStatus.data?.supported === false} onClick={() => installHook.mutate()} className="mt-3 flex h-9 w-full items-center justify-center gap-2 rounded-md border border-zinc-300 bg-white text-[11px] font-medium text-zinc-700 hover:bg-zinc-50 disabled:cursor-not-allowed disabled:opacity-40"><Wrench size={12}/>{installHook.isPending ? '正在检测并配置 Hook' : hookStatus.data?.installed ? '重新检测并配置 Hook' : '检测并配置 Hook'}</button>
            {hookStatus.data?.supported === false && <div className="mt-2 rounded-md border border-amber-200 bg-amber-50 px-2.5 py-2 text-[10px] leading-4 text-amber-800">{hookStatus.data.reason}</div>}
            {hookStatus.data?.trustInstructions && <div className="mt-2 rounded-md border border-zinc-200 bg-white px-2.5 py-2 text-[10px] leading-4 text-zinc-500">{hookStatus.data.trustInstructions}</div>}
          </div>}
          </>}
        </>}
        {formError && <div className="rounded-md border border-red-100 bg-red-50 px-2.5 py-2 text-[11px] leading-4 text-red-700"><div>{formError.message}</div>{permissionRelatedError && permissionSettingsUrl && <a href={permissionSettingsUrl} target="_blank" rel="noreferrer" className="mt-2 inline-flex items-center gap-1 font-medium text-red-800 underline decoration-red-300 underline-offset-2 hover:text-red-950">打开当前机器人的权限配置<ExternalLink size={11}/></a>}</div>}
      </div>
      <div className="flex items-center border-t border-zinc-100 px-4 py-3">{current ? <button type="button" onClick={() => { remove.reset(); setConfirmation('delete'); }} className="flex items-center gap-1.5 rounded-md px-2 py-1.5 text-[11px] font-medium text-red-600 hover:bg-red-50"><Trash2 size={13}/>删除配置</button> : <span className="text-[10px] text-zinc-400">App ID 将作为唯一主键，不能重复配置</span>}{step === 2 && <button type="button" onClick={() => setStep(1)} className="ml-auto rounded-md px-3 py-1.5 text-xs font-medium text-zinc-600 hover:bg-zinc-100">上一步</button>}<button type="button" onClick={requestClose} className={`${step === 2 ? '' : 'ml-auto'} rounded-md px-3 py-1.5 text-xs font-medium text-zinc-600 hover:bg-zinc-100`}>{step === 2 && current && !current.setupComplete ? '稍后完成' : '取消'}</button><button type="submit" disabled={!canSave || save.isPending} className="ml-1 min-w-20 rounded-md bg-zinc-900 px-3 py-1.5 text-xs font-medium text-white hover:bg-zinc-700 active:scale-[.98] disabled:cursor-not-allowed disabled:opacity-35">{save.isPending ? (step === 1 ? '验证中' : '保存中') : agentCapabilitiesPending ? '读取模型中' : step === 1 ? '下一步' : '完成配置'}</button></div>
    </form>
  </div><ConfirmDialog
    open={Boolean(confirmation)}
    tone={confirmation === 'delete' ? 'danger' : 'warning'}
    title={confirmation === 'delete' ? '删除机器人配置？' : confirmation === 'incomplete' ? '稍后再完成配置？' : '放弃未保存的配置？'}
    description={confirmation === 'delete' ? `将删除“${current?.name ?? '当前机器人'}”的凭证、监听和门禁配置。已有会话记录不会删除。` : confirmation === 'incomplete' ? 'Agent 配置尚未完成。若已开启监听，机器人仍会接收消息，并提示发送人补充运行配置。' : '当前填写的机器人信息尚未保存，关闭后需要重新填写。'}
    confirmLabel={confirmation === 'delete' ? '确认删除' : confirmation === 'incomplete' ? '稍后完成' : '放弃修改'}
    busy={confirmation === 'delete' && remove.isPending}
    error={confirmation === 'delete' && remove.error ? remove.error.message : undefined}
    onCancel={() => { if (!remove.isPending) setConfirmation(undefined); }}
    onConfirm={() => { if (confirmation === 'delete') remove.mutate(); else { setConfirmation(undefined); onClose(); } }}
  /></>;
}
